name: image_event_scheduler
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  path_provider: ^2.0.15
  http: ^1.2.1
  intl: ^0.20.2
  google_sign_in: ^5.4.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  url_launcher: ^6.1.10
  device_calendar: ^4.3.2
  timezone: ^0.9.4
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  # Maps and Location
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  geocoding: ^2.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
